# Generated by Django 4.2.28 on 2026-03-11 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='name',
            field=models.CharField(error_messages={'max_length': 'Dessert name cannot exceed 100 characters.', 'unique': 'A dessert with this name already exists.'}, help_text='Enter the name of the dessert.', max_length=100, unique=True, verbose_name='Dessert Name'),
        ),
    ]
