# Generated by Django 4.2.28 on 2026-03-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0002_alter_dessert_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='image',
            field=models.ImageField(default=1, help_text='Upload an image of the dessert.', upload_to='desserts/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
