# Generated by Django 4.2.28 on 2026-03-12 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0003_alter_dessert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='image',
            field=models.ImageField(blank=True, default='desserts/no-image.jpg', help_text='Upload an image of the dessert.', null=True, upload_to='desserts/', verbose_name='Image'),
        ),
    ]
