# Generated by Django 4.2.28 on 2026-03-12 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0004_alter_dessert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='image',
            field=models.ImageField(default=1, error_messages={'invalid': 'Please upload a valid image file.', 'required': 'An image is required for this dessert.'}, help_text='Upload an image of the dessert.', upload_to='desserts/', verbose_name='Image'),
            preserve_default=False,
        ),
    ]
