# Generated by Django 4.2.28 on 2026-04-07 12:15

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desserts', '0005_alter_dessert_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dessert',
            name='image',
            field=cloudinary.models.CloudinaryField(max_length=255, verbose_name='image'),
        ),
    ]
